version: "3"

services:
  flask-app:
    image: sepro/flask-app:latest
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "5000:5000"
    networks:
      - backend
    depends_on:
      - database
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=user
      - POSTGRES_DB=app
      - POSTGRES_URI=database

  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - backend
    volumes:
      - ./utils/db:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_USER=user
      - POSTGRES_DB=app

networks:
  backend:
